### PR TITLE
Adds Russian translation for README.md

### PR DESCRIPTION
**Pull request by Qussth**

### CODE REVIEW

**Comment by Arashi5** [comment]
Terrible translation. Feels like machine translation has been used.

**Comment by Qussth** [comment]
Not a single time. All translation made by myself, as close to origin text as possible. I think it`s still better than no russian translation at all.

**Comment by kcq** [comment]
Thanks a lot for the PR @Qussth ! Happy to merge... There might be a minor typo on line 72: "Подумайте б этом". Do you mind updating the PR.

**Comment by Qussth** [comment]
@kcq Sure, thank you!

**Comment by kcq** [comment]
> @kcq Sure, thank you!

Nice!

**Pull request merged**
