### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jcambrosi**
Portuguese > Português (as it is in portuguese language)

### CODE REVIEW

**Review by mimani68 — APPROVED** [review]

**Review by rrgaya — APPROVED** [review]

**Comment by jcambrosi** [comment]
It appears I cannot merge. Need more approvals (have 2) or am I missing something?

**Comment by rrgaya** [comment]
Look 

"Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Comment by jcambrosi** [comment]
Yeah, I saw that ... so we just wait for someone with write-access to take the initiative and do the merge?

**Comment by rrgaya** [comment]
Yep

**Comment by jcambrosi** [comment]
well, ok, thanks

**Comment by kcq** [comment]
thanks for the update @jcambrosi !

**Pull request merged**
